site_name: CL Documentation
theme: readthedocs
markdown_extensions:
  - toc:
      permalink: True  
nav:
  - Getting started: index.md
  - Cite: cite.md
  - History: history.md
  - How-to guides:
      - Standard ODK workflows:
          - Overview: odk-workflows/index.md
          - Editors Workflow: odk-workflows/EditorsWorkflow.md
          - Release Workflow: odk-workflows/ReleaseWorkflow.md
          - Manage your ODK Repository: odk-workflows/RepoManagement.md
          - Setting up Docker for ODK: odk-workflows/SettingUpDockerForODK.md
          - Importing classes from another ontology: Adding_classes_from_another_ontology.md
          - Imports management: odk-workflows/UpdateImports.md
          - Managing the documentation: odk-workflows/ManageDocumentation.md
          - Continuous Integration: odk-workflows/ContinuousIntegration.md
          - Your ODK Repository Overview: odk-workflows/RepositoryFileStructure.md 
      - Contributing: contributing.md
  - Design Patterns:
    - Design Patterns Overview: patterns/overview.md
    - Cell, bearer of quality: patterns/cellBearerOfQuality.md
    - Cell, has plasme membrane: patterns/cellHasPlasmaMembranePartX.md
    - Cell, capable of Biological Process: patterns/cellCapableOfBiologicalProcess.md
    - Cell, part of anatomical entity: patterns/cellPartOfAnatomicalEntity.md
    - Cell, taxon specific: patterns/taxonSpecific.md
  - CL Internal Docs:
      - Keep terms up-to-date: Keeping_ontology_terms_up_to_date.md
      - CL annotation properties: annotation_properties.md
      - CL presentations: presentations.md
      - CL relations: relations_guide.md
      - CL release: cl-release.md
      - How to resolve merge conflicts: resolving_merge_conflicts.md
      - Fixing unintended ^^xsd:string diffs: Fixing_xsdstring_diffs.md
      - Taxon constraints: taxon-restrictions.md
  - Contact: contact_us.md

