name: Post release diff

on:
  # Triggers the workflow on pull request events for the master branch
  pull_request:
    branches: [ master ]
    paths:
      - 'src/ontology/diffs/cl-diff.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  post_diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare release comment
        env:
            GITHUB_SHA: ${{ github.sha }}
        run: "echo \"[Here's a diff of how this release impacts cl-simple.owl](https://github.com/obophenotype/cell-ontology/blob/${{ env.GITHUB_SHA }}/src/ontology/reports/cl-simple-diff.md)\" >comment.md"
      - name: Post reasoned comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: NejcZdovc/comment-pr@v1.1.1
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          file: "../../comment.md"
          identifier: "CL-DIFF"